import { join } from "node:path";
import { z } from "zod";
import { answerRescue, CLIMB_FILES, LINE_TARGET, sign, signLine } from "../basecamp/desk.ts";
import { climbDir } from "../basecamp/event-log.ts";
import { settle } from "../domain/decisions.ts";
import { RESCUE_OPTIONS } from "../domain/types.ts";
import { isDir, readText, sha256 } from "../util/fs.ts";
import type { ClimbHub } from "./hub.ts";

/** Climb ids are generated by us; anything else could be a path traversal attempt. */
const climbId = z.string().regex(/^[\w-]+$/);

const commandSchema = z.discriminatedUnion("cmd", [
  z.strictObject({
    cmd: z.literal("sign"),
    climb: climbId,
    hash: z.string().min(8),
    target: z
      .string()
      .regex(/^[\w-]+$/)
      .optional(),
    choices: z.record(z.string().regex(/^D\d+$/), z.string().min(1).max(200)).optional(),
  }),
  z.strictObject({ cmd: z.literal("rescue"), climb: climbId, option: z.enum(RESCUE_OPTIONS) }),
]);

type Command = z.infer<typeof commandSchema>;
type CommandOf<C extends Command["cmd"]> = Extract<Command, { cmd: C }>;

export type CommandOutcome = { ok: true } | { ok: false; message: string };

interface CommandContext<C extends Command["cmd"]> {
  command: CommandOf<C>;
  dir: string;
  hub: ClimbHub;
}

/** The only two things a browser can ask for: a signature and a rescue answer. Both become files the Basecamp reads. */
const HANDLERS: { [C in Command["cmd"]]: (ctx: CommandContext<C>) => CommandOutcome } = {
  sign: ({ command, dir, hub }) => {
    const target = command.target ?? LINE_TARGET;
    if (target !== LINE_TARGET) {
      // Bolts e summit: assina o hash que a pessoa viu; o Basecamp recusa se já não for o atual.
      const pending = hub.view(command.climb)?.signatures.find((s) => s.target === target && !s.signed);
      if (!pending) return { ok: false, message: "Nada com esse nome espera assinatura." };
      if (pending.hash !== command.hash)
        return { ok: false, message: "Isto mudou desde que você abriu. Leia a versão nova antes de assinar." };
      sign(dir, target, command.hash, "lookout");
      return { ok: true };
    }
    // Assina só o texto que a pessoa viu: se a line mudou desde então, recusa.
    if (sha256(readText(join(dir, CLIMB_FILES.line)) ?? "") !== command.hash) {
      return { ok: false, message: "A line mudou desde que você abriu. Leia a versão nova antes de assinar." };
    }
    const { problems } = settle(hub.view(command.climb)?.line?.decisions ?? [], command.choices);
    if (problems.length) return { ok: false, message: problems.join("; ") };
    signLine(dir, "lookout", command.choices);
    return { ok: true };
  },

  rescue: ({ command, dir, hub }) => {
    if (!hub.view(command.climb)?.rescue?.options.includes(command.option)) {
      return { ok: false, message: "Esta opção de rescue não está disponível." };
    }
    answerRescue(dir, command.option, "lookout");
    return { ok: true };
  },
};

export function handleCommand(raw: string, mohsDir: string, hub: ClimbHub): CommandOutcome & { cmd?: string } {
  const parsed = commandSchema.safeParse(safeJson(raw));
  if (!parsed.success) return { ok: false, message: "Comando inválido." };

  const command = parsed.data;
  const dir = climbDir(mohsDir, command.climb);
  if (!isDir(dir)) return { ok: false, message: "Climb não encontrado." };

  const handler = HANDLERS[command.cmd] as (ctx: CommandContext<Command["cmd"]>) => CommandOutcome;
  return { ...handler({ command, dir, hub }), cmd: command.cmd };
}

function safeJson(raw: string): unknown {
  try {
    return JSON.parse(raw);
  } catch {
    return undefined;
  }
}
